"""
Parity tests for PyTorch vs ONNX YOLO11n — M6.

Run with:
    .venv\\Scripts\\python.exe -m pytest tests/test_onnx_parity.py -v

Requires:
    - models/yolo11n.pt
    - models/yolo11n.onnx
    - data/input.mp4
    - outputs/onnx_parity.json  (generated by tools/compare_pytorch_onnx.py)
"""

from __future__ import annotations

import json
import os
import subprocess
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PARITY_JSON = os.path.join(
    os.path.dirname(__file__), "..", "outputs", "onnx_parity.json"
)
PYTORCH_MODEL = os.path.join(
    os.path.dirname(__file__), "..", "models", "yolo11n.pt"
)
ONNX_MODEL = os.path.join(
    os.path.dirname(__file__), "..", "models", "yolo11n.onnx"
)
COMPARE_SCRIPT = os.path.join(
    os.path.dirname(__file__), "..", "tools", "compare_pytorch_onnx.py"
)
VIDEO_PATH = os.path.join(
    os.path.dirname(__file__), "..", "data", "input.mp4"
)

# Acceptance thresholds (generous — accounts for FP32 vs ORT precision)
MIN_ACCEPTABLE_MEAN_IOU = 0.80
MAX_ACCEPTABLE_MEAN_CONF_DIFF = 0.10


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def parity_json() -> dict:
    """Load onnx_parity.json, skipping if not present."""
    if not os.path.isfile(PARITY_JSON):
        pytest.skip(
            f"Parity JSON not found: {PARITY_JSON}. "
            "Run: python tools/compare_pytorch_onnx.py"
        )
    with open(PARITY_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# File existence
# ---------------------------------------------------------------------------

class TestFilesExist:
    def test_onnx_model_exists(self):
        if not os.path.isfile(ONNX_MODEL):
            pytest.skip("ONNX model not found — run export_onnx.py first")
        assert os.path.isfile(ONNX_MODEL)

    def test_parity_json_exists(self):
        if not os.path.isfile(PARITY_JSON):
            pytest.skip("Parity JSON not found — run compare_pytorch_onnx.py first")
        assert os.path.isfile(PARITY_JSON)


# ---------------------------------------------------------------------------
# JSON structure tests
# ---------------------------------------------------------------------------

class TestParityJSONStructure:
    def test_json_is_parseable(self, parity_json):
        assert isinstance(parity_json, dict)

    def test_has_metadata(self, parity_json):
        assert "metadata" in parity_json
        meta = parity_json["metadata"]
        assert "pytorch_model" in meta
        assert "onnx_model" in meta
        assert "onnx_provider" in meta
        assert "frames" in meta

    def test_has_summary(self, parity_json):
        assert "summary" in parity_json
        s = parity_json["summary"]
        assert "frames_compared" in s
        assert "matching_detection_count_frames" in s
        assert "total_matched_pairs" in s
        assert "mean_bbox_iou" in s
        assert "min_bbox_iou" in s
        assert "mean_confidence_diff" in s
        assert "max_confidence_diff" in s

    def test_has_frames_list(self, parity_json):
        assert "frames" in parity_json
        assert isinstance(parity_json["frames"], list)
        assert len(parity_json["frames"]) > 0

    def test_frame_entries_have_required_keys(self, parity_json):
        for fr in parity_json["frames"]:
            assert "frame_index" in fr
            assert "pytorch_count" in fr
            assert "onnx_count" in fr
            assert "matches" in fr
            assert isinstance(fr["matches"], list)

    def test_provider_is_reported(self, parity_json):
        provider = parity_json["metadata"]["onnx_provider"]
        assert isinstance(provider, str)
        assert len(provider) > 0
        assert provider in (
            "CUDAExecutionProvider",
            "CPUExecutionProvider",
            "TensorrtExecutionProvider",
        ), f"Unexpected provider: {provider!r}"

    def test_frames_compared_is_positive(self, parity_json):
        assert parity_json["summary"]["frames_compared"] > 0


# ---------------------------------------------------------------------------
# Parity quality tests
# ---------------------------------------------------------------------------

class TestParityQuality:
    def test_mean_iou_above_threshold(self, parity_json):
        mean_iou = parity_json["summary"]["mean_bbox_iou"]
        if mean_iou is None:
            pytest.skip("No matched pairs — no detections on any parity frame")
        assert mean_iou >= MIN_ACCEPTABLE_MEAN_IOU, (
            f"Mean IoU {mean_iou:.4f} < threshold {MIN_ACCEPTABLE_MEAN_IOU}. "
            "Possible preprocessing mismatch."
        )

    def test_mean_confidence_diff_acceptable(self, parity_json):
        mean_diff = parity_json["summary"]["mean_confidence_diff"]
        if mean_diff is None:
            pytest.skip("No matched pairs")
        assert mean_diff <= MAX_ACCEPTABLE_MEAN_CONF_DIFF, (
            f"Mean confidence diff {mean_diff:.4f} > {MAX_ACCEPTABLE_MEAN_CONF_DIFF}. "
            "Possible postprocessing mismatch."
        )

    def test_all_match_entries_have_iou_field(self, parity_json):
        for fr in parity_json["frames"]:
            for m in fr["matches"]:
                assert "iou" in m
                assert isinstance(m["iou"], float)
                assert 0.0 <= m["iou"] <= 1.0

    def test_all_match_entries_have_confidence_diff(self, parity_json):
        for fr in parity_json["frames"]:
            for m in fr["matches"]:
                assert "confidence_diff" in m
                assert isinstance(m["confidence_diff"], float)
                assert m["confidence_diff"] >= 0.0


# ---------------------------------------------------------------------------
# Script smoke test
# ---------------------------------------------------------------------------

class TestParityScript:
    def test_compare_script_produces_valid_json(self):
        """Run compare_pytorch_onnx.py and verify it produces valid JSON."""
        if not os.path.isfile(ONNX_MODEL):
            pytest.skip("ONNX model not found — run export_onnx.py first")

        # Use workspace-local outputs dir to avoid Windows %TEMP% permission issues
        out_dir = os.path.join(os.path.dirname(__file__), "..", "outputs")
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, "onnx_parity_smoke_test.json")

        result = subprocess.run(
            [
                sys.executable,
                COMPARE_SCRIPT,
                "--source", VIDEO_PATH,
                "--pytorch-model", PYTORCH_MODEL,
                "--onnx-model", ONNX_MODEL,
                "--output", out_path,
            ],
            capture_output=True,
            text=True,
            timeout=300,
        )
        assert result.returncode == 0, (
            f"compare_pytorch_onnx.py failed:\n"
            f"stdout: {result.stdout}\n"
            f"stderr: {result.stderr}"
        )
        assert os.path.isfile(out_path), "JSON output file not created"
        with open(out_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "summary" in data
        assert "frames" in data

        # Cleanup temp file
        try:
            os.remove(out_path)
        except OSError:
            pass
